name: Common Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: daaa1k/common-lint@c0ad902f6ab4f8fae060b6ce76913a8ddba3a531 # v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
